### ISSUE TITLE
[Bug]: JpLocalGov.valid_code?の結果が正しくない

### ISSUE THREAD

**Issue by ryu** [IkumaTadokoro/jp_local_gov#85]
### Summary

JpLocalGov.valid_code?の結果が正しくない場合があります。

### Steps to reproduce the bug

```ruby
# OK
local_gov = JpLocalGov.where(city: "宇都宮市").first
local_gov.code #=> "092011"
JpLocalGov.valid_code?(local_gov.code) #=> true

# NG
local_gov = JpLocalGov.where(city: "札幌市中央区").first
local_gov.code #=> "011011"
JpLocalGov.valid_code?(local_gov.code) #=> false
```

### Expected

札幌市中央区('011011')の場合も`JpLocalGov.valid_code?`がtrueを返すこと。

### Environment

以下の環境で確認しました。

- Ruby 3.1.0
- jp_local_gov 0.3.0

**Comment by IkumaTadokoro** [comment]
@ryu 
バグ報告ありがとうございます！とても助かります！🙏

## 原因

チェックディジットはJISX0402に基づき、以下のような判定処理をしています。

> 第１桁から第５桁までの数字に、それぞれ６．５．４．３．２を乗じて算出した積の和を求め、その和を１１で除し、商と剰余（以下「余り数字」という。）を求めて、１１と余り数字との差の下１桁の数字を検査数字とする。
ただし、積の和が１１より小なるときは、検査数字は、１１から積の和を控除した数字とする。
https://www.soumu.go.jp/main_content/000137948.pdf

このうち

> 積の和が１１より小なるとき

の部分が修正前の動作では「11以下になるとき」となっていました
（積の和が11になるケースはご報告いただいた「札幌市中央区」のみでした）。

## 対応

JISX0402のとおりにチェックが行われるように、#86 で修正しました。
なおこの修正はv0.3.1でリリースする予定です。
